# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MSFindPerfectCoresUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MSFindPerfectCores(object):
    def setupUi(self, MSFindPerfectCores):
        MSFindPerfectCores.setObjectName("MSFindPerfectCores")
        MSFindPerfectCores.setWindowModality(QtCore.Qt.NonModal)
        MSFindPerfectCores.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MSFindPerfectCores)
        self.centralwidget.setObjectName("centralwidget")
        MSFindPerfectCores.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MSFindPerfectCores)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MSFindPerfectCores.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MSFindPerfectCores)
        self.statusbar.setObjectName("statusbar")
        MSFindPerfectCores.setStatusBar(self.statusbar)

        self.retranslateUi(MSFindPerfectCores)
        QtCore.QMetaObject.connectSlotsByName(MSFindPerfectCores)

    def retranslateUi(self, MSFindPerfectCores):
        _translate = QtCore.QCoreApplication.translate
        MSFindPerfectCores.setWindowTitle(_translate("MSFindPerfectCores", "MSFindPerfectCores"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MSFindPerfectCores = QtWidgets.QMainWindow()
    ui = Ui_MSFindPerfectCores()
    ui.setupUi(MSFindPerfectCores)
    MSFindPerfectCores.show()
    sys.exit(app.exec_())
